### ISSUE TITLE
Add possibility to have interactive password

### ISSUE THREAD

**Issue by dezechristophe** [YPSI-SAS/centctl#11]
**Is your feature request related to a problem? Please describe.**
I don't want the password to be written in a file or in bash history
**Describe the solution you'd like**
Is ti possible to have an argument that force the cli to ask for a password ?

**Comment by MelissaB79** [comment]
Hello,

The management of the password is added in the last release. You have two possibilities for manage the passwords. Either you don't write the password into the yaml file and the CLI ask you to give the password in the terminal or you encrypt the passwords present in the config file with encrypt command. For more details, you can consult the readme.
