### ISSUE TITLE
Add posibility to remove a host template from host object

### ISSUE THREAD

**Issue by Nedyaz** [YPSI-SAS/centctl#21]
**Is your feature request related to a problem? Please describe.**
I was trying to remove a host template from a host using 'centctl modify host' but after looking at the documentation, help and source code it seems that it's not possible

**Describe the solution you'd like**
I'd like to have something like this 
centctl modify host --name MYHOST--parameter template --value OS-Windows-NSClient-05-NRPE-custom --operation remove  --server PROD

**Describe alternatives you've considered**
We could use CLAPI or Centreon API to do this but I'd rather use CentCTL :)

**Additional context**
Nothing to add...

Thanks in advance for taking this request into account

**Comment by MelissaB79** [comment]
hello,

I just corrected that in the last release. 
The operation flag has been added for all objects requiring it. (host, service, template, category etc).

Thank you for your contribution to improving the tool.
