### ISSUE TITLE
Change field name in result of some command to fix English mistakes

### ISSUE THREAD

**Issue by olivier-monaco** [YPSI-SAS/centctl#24]
Fields to rename in result of some command:
* `list host`, `list service`, `show service`, `show host`...
  * rename `activate` to `active`
* `show host`
  * rename `childs` to `children`
* `list poller`
  * rename `is_activate` to `is_active`

**Comment by MelissaB79** [comment]
hello,

I renamed childs to children but for "is_activate" and "activate" I don't changed because it is write like that in centreon's documentation.

Thank you for your contribution to improving the tool.
