### ISSUE TITLE
Error 200 - show command

### ISSUE THREAD

**Issue by Arawn777** [YPSI-SAS/centctl#26]
Hi Melissa!

Here is the issue I told you:

Environment:
Centreon 21.04
CentCTL 2.5.7 in wsl oraclelinux 8_5 => VScode Terminal on Win11

centctl.yaml:

servers:
\- server: "FR-CENTREON-CENTRAL"
    url: "https://**********.com/centreon"
    insecure: true
    login: "LOGIN"
    password: "PASSWORD"
    version: "v1"
    default: true

While executing the show command, I got an error 200 in response:

![image](https://github.com/YPSI-SAS/centctl/assets/94179123/7cf39978-9bbc-48a5-b097-5f3b23089aec)

Executing this same command in DEBUG mode, here is the answer:

![image](https://github.com/YPSI-SAS/centctl/assets/94179123/ca9d1280-4db8-463f-9592-5b65fcf89e03)

No issues with list or add command

Thanks in advance :)

**Comment by Arawn777** [comment]
Same problem on a WSL debian to manage a Centreon 23.04.9, and also with the export command that returns an error 200. The DEBUG mode shows the command returns the results expected in the body response.

**Comment by MelissaB79** [comment]
hello,

I just corrected that in the last release.

Thank you for your contribution to improving the tool.
