### ISSUE TITLE
Error 200 - realtime command

### ISSUE THREAD

**Issue by grosbedos** [YPSI-SAS/centctl#31]
Hi,

I have the same behavior as issue 26, but for realtime command.

`$ ./centctl list realtimeService --limit 10 -v unhandled -r "Disk.*"`
`ERROR: 200`

If i do the same with debug mode, i have the body response which looks good, but with the error at the end.
Same thing with realtimeHost.

Environment:
Centreon 23.10.5
cenctl 2.5.8
debian 12
I am using v2 API version

Best regard

**Comment by vcoumailleau** [comment]
Hello,

The v2.5.9 should fix your problem
https://github.com/YPSI-SAS/centctl/releases/tag/v2.5.9
Can you test it and tell me if you still have the error?

Thanks

Regards

**Comment by grosbedos** [comment]
it works perfectly !

Thanks a lot
