### ISSUE TITLE
Realtime : states all not supported

### ISSUE THREAD

**Issue by grosbedos** [YPSI-SAS/centctl#32]
Hi,

Using the realtime command, I can only list unhandled states.
All is not recognized.

`./centctl list realtimeService --limit 10 -v all -r "Disk.*" --DEBUG`
`[INFO]  2024/02/06 09:13:11 centctl authentification - successful authentification, token generate`
`[INFO]  2024/02/06 09:13:11 centctl list realtimeService - URL: /monitoring/resources?limit=10&types=["service"]&statuses=["OK","CRITICAL","WARNING","UNKNOWN","PENDING"]&states=["all"]`
`[ERROR] 2024/02/06 09:13:11 centctl/debug.Show:debug.go:46 centctl list realtimeService - statusCode: 500`
`[ERROR] 2024/02/06 09:13:11 centctl/debug.Show:debug.go:47 centctl list realtimeService - Body response: {"code":4,"message":"Value provided for states parameter is not supported (was: all)"}`

Environment:
Centreon 23.10.5
cenctl 2.5.8
debian 12
I am using v2 API version

Best regard

**Comment by vcoumailleau** [comment]
Hello,

Indeed i have the same error
I did some modification to the realtime listing requests

Can you try with the pre-release version (v2.5.9) and tell me if it fix the problem on your side? 

https://github.com/YPSI-SAS/centctl/releases/tag/v2.5.9


Regards

**Comment by grosbedos** [comment]
Thanks for the quick response, it's resolved.

Best regard
